server:
  port: ${NOTIFICATION_SERVICE_PORT}
  servlet:
    context-path: ${NOTIFICATION_SERVICE_CONTEXT_PATH}

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL}
  instance:
    preferIpAddress: true

spring:
  application:
    name: ${NOTIFICATION_SERVICE_NAME}

  # Database configuration
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${NOTIFICATION_SERVICE_DATABASE}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

