server:
  port: ${GATEWAY_SERVICE_PORT}

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL}
  instance:
    preferIpAddress: true


logging:
  level:
    root: info # default logger that applies to all packages in the application
    org.springframework: debug
  file:
    name: ./${spring.application.name}/logs/app.log
  logback:
    rollingpolicy:
      file-name-pattern: app_%d{dd-MM-yyyy}_%i.log
      max-file-size: 10MB # Maximum size for each log file (e.g., 10MB). A new file is created when reached
      total-size-cap: 1GB # Total size limit for all log files (e.g., 1GB), the Older files are deleted if exceeded
      max-history: 7 # Maximum number of log files to keep (e.g., 7 days), the Older files were deleted to maintain this limit.
#      clean-history-on-start: true # Clean up the history log files on application start


spring:
  application:
    name: ${GATEWAY_SERVICE_NAME}

  cloud:
    gateway:
      routes:
        - id: ${USER_SERVICE_NAME}
          uri: lb://${USER_SERVICE_NAME}
          predicates:
            - Path=/${USER_SERVICE_NAME}/**

        - id: ${MOVIE_SERVICE_NAME}
          uri: lb://${MOVIE_SERVICE_NAME}
          predicates:
            - Path=/${MOVIE_SERVICE_NAME}/**

        - id: ${BOOKING_SERVICE_NAME}
          uri: lb://${BOOKING_SERVICE_NAME}
          predicates:
            - Path=/${BOOKING_SERVICE_NAME}/**

        - id: ${PAYMENT_SERVICE_NAME}
          uri: lb://${PAYMENT_SERVICE_NAME}
          predicates:
            - Path=/${PAYMENT_SERVICE_NAME}/**

        - id: ${FEEDBACK_SERVICE_NAME}
          uri: lb://${FEEDBACK_SERVICE_NAME}
          predicates:
            - Path=/${FEEDBACK_SERVICE_NAME}/**

        - id: ${NOTIFICATION_SERVICE_NAME}
          uri: lb://${NOTIFICATION_SERVICE_NAME}
          predicates:
            - Path=/${NOTIFICATION_SERVICE_NAME}/**