server:
  port: ${GATEWAY_SERVICE_PORT}

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL}
  instance:
    preferIpAddress: true

spring:
  application:
    name: ${GATEWAY_SERVICE_NAME}

  cloud:
    gateway:
      routes:
        - id: ${USER_SERVICE_NAME}
          uri: lb://${USER_SERVICE_NAME}
          predicates:
            - Path=/${USER_SERVICE_NAME}/**

        - id: ${MOVIE_SERVICE_NAME}
          uri: lb://${MOVIE_SERVICE_NAME}
          predicates:
            - Path=/${MOVIE_SERVICE_NAME}/**

        - id: ${BOOKING_SERVICE_NAME}
          uri: lb://${BOOKING_SERVICE_NAME}
          predicates:
            - Path=/${BOOKING_SERVICE_NAME}/**

        - id: ${PAYMENT_SERVICE_NAME}
          uri: lb://${PAYMENT_SERVICE_NAME}
          predicates:
            - Path=/${PAYMENT_SERVICE_NAME}/**

        - id: ${FEEDBACK_SERVICE_NAME}
          uri: lb://${FEEDBACK_SERVICE_NAME}
          predicates:
            - Path=/${FEEDBACK_SERVICE_NAME}/**

        - id: ${NOTIFICATION_SERVICE_NAME}
          uri: lb://${NOTIFICATION_SERVICE_NAME}
          predicates:
            - Path=/${NOTIFICATION_SERVICE_NAME}/**