server:
  port: 8081
  servlet:
    context-path: /user-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

logging:
  level:
    root: INFO
    com.legend: DEBUG

spring:
  application:
    name: user-service

  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/user-database
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


app:
  keycloak:
    server-url: http://localhost:8080
    realm: movie-ticket-booking-realm
    client-id: user-service
    client-secret: K3SOD7RG4GaRYMJpgpemyaGgpw3YRLpe
    username-super-admin: super-admin
    password-super-admin: 123
    email-super-admin: super.admin@gmail.com
    first-name-super-admin: admin
    last-name-super-admin: admin

